CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT
    TYPE = PARQUET
    COMPRESSION = SNAPPY;
CREATE OR REPLACE STAGE PARQUET_STAGE FILE_FORMAT = PARQUET_FORMAT;
PUT file:///opt/airflow/SCRIPTS/DATA_INSTALLER/i2b2-data/edu.harvard.i2b2.data/Release_1-8/NewInstall/Crcdata/act/scripts/snowflake/*.snappy.parquet @PARQUET_STAGE PARALLEL=4 AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
COPY INTO CONCEPT_DIMENSION FROM @PARQUET_STAGE/CONCEPT_DIMENSION MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT;