/*********************************************************
*         SNOWFLAKE SCRIPT TO LOAD ACT METADATA TABLES
*         MD SABER HOSSAIN	7/14/2023
/*        University of Missouri-Columbia			
**********************************************************/

--- CREATE FILE FORMAT
CREATE OR REPLACE FILE FORMAT import_format
TYPE = CSV
FIELD_DELIMITER = '\t'
EMPTY_FIELD_AS_NULL = true
TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
NULL_IF = ()
COMPRESSION=NONE
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1;

--- CREATE STAGE AREA
CREATE OR REPLACE STAGE import_metadata FILE_FORMAT = import_format;

-- PUT LOCAL FILES INTO SNOWFLAKE STAGE
PUT file:///home/i2b2-data/edu.harvard.i2b2.data/Release_1-7/NewInstall/Metadata/act/scripts/snowflake/*.csv @import_metadata AUTO_COMPRESS=FALSE SOURCE_COMPRESSION=NONE OVERWRITE=TRUE;


--- COPY ONTOLOGY TABLES FROM THE STAGE
TRUNCATE ACT_COVID_V4;
TRUNCATE ACT_CPT4_PX_V4;
TRUNCATE ACT_DEM_V4;
TRUNCATE ACT_HCPCS_PX_V4;
TRUNCATE ACT_ICD10CM_DX_V4;
TRUNCATE ACT_ICD10PCS_PX_V4;
TRUNCATE ACT_ICD10_ICD9_DX_V4;
TRUNCATE ACT_ICD9CM_DX_V4;
TRUNCATE ACT_ICD9CM_PX_V4;
TRUNCATE ACT_SDOH_V4;
TRUNCATE ACT_VISIT_DETAILS_V4;
TRUNCATE ACT_VITAL_SIGNS_V4;
TRUNCATE ACT_LOINC_LAB_PROV_V4;
TRUNCATE ACT_LOINC_LAB_V4;
TRUNCATE ACT_MED_ALPHA_V4;
TRUNCATE ACT_MED_VA_V4;
TRUNCATE SCHEMES;
TRUNCATE TABLE_ACCESS;

COPY INTO ACT_COVID_V4 from @import_metadata/ACT_COVID_V4.csv;
COPY INTO ACT_CPT4_PX_V4 from @import_metadata/ACT_CPT4_PX_V4.csv;
COPY INTO ACT_DEM_V4 from @import_metadata/ACT_DEM_V4.csv;
COPY INTO ACT_HCPCS_PX_V4 from @import_metadata/ACT_HCPCS_PX_V4.csv;
COPY INTO ACT_ICD10CM_DX_V4 from @import_metadata/ACT_ICD10CM_DX_V4.csv;
COPY INTO ACT_ICD10PCS_PX_V4 from @import_metadata/ACT_ICD10PCS_PX_V4.csv;
COPY INTO ACT_ICD10_ICD9_DX_V4 from @import_metadata/ACT_ICD10_ICD9_DX_V4.csv;
COPY INTO ACT_ICD9CM_DX_V4 from @import_metadata/ACT_ICD9CM_DX_V4.csv;
COPY INTO ACT_ICD9CM_PX_V4 from @import_metadata/ACT_ICD9CM_PX_V4.csv;
COPY INTO ACT_SDOH_V4 from @import_metadata/ACT_SDOH_V4.csv;
COPY INTO ACT_VISIT_DETAILS_V4 from @import_metadata/ACT_VISIT_DETAILS_V4.csv;
COPY INTO ACT_VITAL_SIGNS_V4 from @import_metadata/ACT_VITAL_SIGNS_V4.csv;
COPY INTO ACT_LOINC_LAB_PROV_V4 from @import_metadata/ACT_LOINC_LAB_PROV_V4.csv;
COPY INTO ACT_LOINC_LAB_V4 from @import_metadata/ACT_LOINC_LAB_V4.csv;
COPY INTO ACT_MED_ALPHA_V4 from @import_metadata/ACT_MED_ALPHA_V4.csv;
COPY INTO ACT_MED_VA_V4 from @import_metadata/ACT_MED_VA_V4.csv;
COPY INTO SCHEMES from @import_metadata/SCHEMES.csv;
COPY INTO TABLE_ACCESS from @import_metadata/TABLE_ACCESS.csv;

